name = "script-ink"
compatibility_date = "2024-12-20"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NODE_ENV = "development"
AI_PROVIDER = "google"
AI_MODEL = "gemini-3-flash-preview"
AI_BASE_URL = "https://generativelanguage.googleapis.com/v1beta"

[[d1_databases]]
binding = "DB"
database_name = "script-ink"
database_id = "7d9699aa-83c3-4032-bcc8-bfeff975edaa"
